name: Google UI Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-with-test-run:
    name: Build with test run
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v3
    - id: setup-JDK11
      name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - id: setup-maven-with-cache
      name: Setup maven with cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - id: maven-test-run
      name: Maven test run
      run: mvn clean test -Dspring.profiles.active=remote -Dcucumber.filter.tags=@google -Djava.util.logging.config.file=logging.properties
    - id: upload-allure-results-to-artifactory
      name: Upload allure results to artifactory
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results

  Allure-report:
    name: Allure report
    runs-on: ubuntu-latest
    needs: Build-with-test-run
    steps:
      - id: download-allure-results
        name: Download allure results
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: allure-results
      - id: get-allure-history
        name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - id: generate-allure-report
        name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ./allure-results
          allure_report: allure-report
          allure_history: allure-history
          gh_pages: gh-pages
          keep_reports: 20
      - id: deploy-report-to-github-pages
        name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
